---
driver:
  name: vagrant

provisioner:
   name: chef_solo

platforms:
  - name: centos-6.6
  - name: macosx
    driver:
      name: vagrant
      provider: virtualbox
      box: jhcook/osx-yosemite-10.10
      username: vagrant
      vm_hostname: macosx
      customize:
        memory: 8192

suites:
  - name: default
    run_list:
      - recipe[resin]
    attributes:
      data_bags_path: test/integration/data_bags